version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - security patch
  ignore:
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: aiohttp
    versions:
    - 3.7.3
  - dependency-name: networkx
    versions:
    - "2.5"
